version: 2
updates:
  - package-ecosystem: nuget
    directories:
      - /
      - /tests/ClassIsland.SchoolStats.Tests
    schedule:
      interval: weekly
    groups:
      test-dependencies:
        patterns:
          - xunit*
          - Microsoft.NET.Test.Sdk
          - coverlet.collector

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: dotnet-sdk
    directory: /
    schedule:
      interval: weekly
